description: "This research project develops training materaisl for researchers wanting to learn to build project websites in Github with Github Pages."
email: "team@carpentries.org"
github: "https://github.com/swcarpentry.org"

team_members: 
  - name: "Sarah Becker"
    role: "project lead"
    start_date: "2016-02-01"
  - name: "Jane Smith"
    role: maintainer
    start_date: "2018-03-15"
  - name: "Albert Hamilton"
    role: editor
    start_date: "2017-12-01"
    
