description: "This research project develops training materaisl for researchers wanting to learn to build project websites in Github with Github Pages."
email: "team@carpentries.org"
github: "https://github.com/swcarpentry.org

